---
title: "load duration curve"
description: |
  visualization of Load duration curves.
date: 2023-01-29
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(timetk)
library(entsoeapi)
library(tidyverse)
library(lubridate)
```

```{r}
## compare countries

zones <- c(
  "10YCH-SWISSGRIDZ", "10YAT-APG------L",
  "10Y1001A1001A82H", "10Y1001A1001A73I"
)

token <- keyring::key_get("entsoe")

load <-
  map_df(
    zones,
    ~ en_load_actual_total_load(
      eic = .x,
      period_start = "2022-01-01",
      period_end = "2022-12-21",
      security_token = token
    )
  )


mean_quantity <- load |>
  group_by(out_bidding_zone) |> 
  summarise(mean_quantity = mean(quantity))
```

## Plot Load duration curves for selected bidding zones
```{r}
load |>
  filter(quantity < 150000) |> 
  group_by(out_bidding_zone) |>
  summarise_by_time(dt, .by = "hour", quantity = mean(quantity)) |> 
  arrange(desc(quantity)) |> 
  mutate(rn = row_number()) |>
  left_join(mean_quantity, by = "out_bidding_zone") |> 
  left_join(en_eic() |> filter(AreaTypeCode == "BZN"), by = c("out_bidding_zone" = "AreaCode")) |> 
  mutate(quantity = quantity / mean_quantity) |>
  ggplot(aes(rn, quantity, color = AreaName, group = AreaName)) +
  geom_line() +
  geom_hline(yintercept = 1)+
  theme_bw()
```

